# Generated by Django 3.2.16 on 2023-01-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(0, 'Uncategorised'), (1, 'Tech'), (2, 'Dogs'), (3, 'Cars')], default=0),
        ),
    ]
