# Generated by Django 3.2.16 on 2023-01-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_auto_20230125_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='Enter Category Here', max_length=30),
        ),
    ]
