# Generated by Django 3.2.16 on 2023-01-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0011_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
